import React,{useState, useEffect} from 'react';
import axios from 'axios';
import Head from 'next/head';


function index() {
  const [data, setData] = useState('');

  const getListContact =()=>{
    axios.get(`https://simple-contact-crud.herokuapp.com/contact`)
    .then((res)=>{
      console.log(res.data)
    })
  }
  
  useEffect(()=>{
    getListContact()
  },[])

  return (
    <div>
      <Head>
        <title>List Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>List Contact</h1>
    </div>
  )
}

export default index
