import Head from 'next/head'
import Image from 'next/image'
import { Container, Button } from 'react-bootstrap';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container >
        <h1>Contact APP</h1>
      </Container>
      
    </div>
  )
}
